import { QRCodeSVG } from 'qrcode.react';
import { QRCode } from '../types/qrcode.types';
import '../styles/PrintPreview.css';

interface PrintPreviewProps {
  qrCodes: QRCode[];
  houseManualName: string;
  onPrint?: () => void;
  onBack?: () => void;
  isPrintMode?: boolean;
}

function PrintPreview({ qrCodes, houseManualName, onPrint, onBack, isPrintMode = false }: PrintPreviewProps) {
  return (
    <div className={`print-preview ${isPrintMode ? 'print-mode' : ''}`}>
      {!isPrintMode && (
        <div className="preview-header">
          <h2>Print Preview</h2>
          <p>{qrCodes.length} QR code{qrCodes.length !== 1 ? 's' : ''} selected for printing</p>
        </div>
      )}

      <div className="print-content">
        {/* Print Header - Only visible when printing */}
        <div className="print-header">
          <h1>{houseManualName}</h1>
          <p>QR Codes for Guest Reference</p>
        </div>

        {/* QR Codes Grid */}
        <div className="print-grid">
          {qrCodes.map(qrCode => (
            <div key={qrCode.id} className="print-qr-card">
              <div className="print-qr-image">
                <QRCodeSVG
                  value={qrCode.content}
                  size={150}
                  level="H"
                  includeMargin={true}
                  bgColor="#ffffff"
                  fgColor="#000000"
                />
              </div>
              <div className="print-qr-info">
                <h3>{qrCode.title}</h3>
                <span className="print-usecase">{qrCode.useCaseName}</span>
              </div>
            </div>
          ))}
        </div>

        {/* Print Footer */}
        <div className="print-footer">
          <p>Generated by Split Lease</p>
        </div>
      </div>

      {!isPrintMode && (
        <div className="preview-actions">
          <button className="btn btn-secondary" onClick={onBack}>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <line x1="19" y1="12" x2="5" y2="12"></line>
              <polyline points="12 19 5 12 12 5"></polyline>
            </svg>
            Back to Edit
          </button>
          <button className="btn btn-primary" onClick={onPrint}>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="6 9 6 2 18 2 18 9"></polyline>
              <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path>
              <rect x="6" y="14" width="12" height="8"></rect>
            </svg>
            Print Now
          </button>
        </div>
      )}
    </div>
  );
}

export default PrintPreview;
